### ISSUE TITLE
'ls' output is dark blue no matter what

### ISSUE THREAD

**Issue by ballPointPenguin** [kyrylo/pry-theme#44]
I'm using pry-theme with urxvt-256color and it seems to be working fine.
Except that the list of methods that pry returns from the ls command is unaffected by the theme.

For example, using the zenburn theme, the ls output is dark blue and white, same as if there was no theme. It's difficult to read dark blue against black (my preferred terminal background color) so I resort to running pry with Pry.config.color = false. :cry:

**Comment by kyrylo** [comment]
Hello, @ballPointPenguin! Thanks for posting this!

That is true, Pry Theme does nothing to `ls`'s output. It's probably something Pry Theme _could_ support now, since Pry has nice API for it (props to @rpag; if I recall correctly since the latest version). So yes, this is definitely doable. The tricky part is messing with each theme and tweaking colours appropriately to each theme.

However, currently, what you can do now is to manually set the `ls` colours via the [config](https://github.com/pry/pry/blob/dd5e2511f3982665950d314e792ec72a99bbe842/lib/pry/commands/ls.rb#L5-L20). Check this out:

```ruby
[8] pry(main)> Pry.config.ls
=> <Pry::Config:0xe3b96c local_keys=['heading_color','public_method_color','private_method_color','protected_method_color','method_missing_color','local_var_color','pry_var_color','instance_var_color','class_var_color','global_var_color','builtin_global_color','pseudo_global_color','constant_color','class_constant_color','exception_constant_color','unloaded_constant_color','separator','ceiling'] default=nil>
```

This is a bunch of colour properties for the `ls` command. Here's how you can modify them per session.

```ruby
[16] pry(main)> _pry_.config.ls.heading_color = :green
```

If you want to make your changes persistent, put the expression inside your `~/.pryrc`.

```ruby
# ~/.pryrc
Pry.config.ls.heading_color = :green
```

I agree this is not very flexible, but as a quick solution it will do absolutely fine!

**Comment by rpag** [comment]
@kyrylo waiting for you on IRC

**Comment by kyrylo** [comment]
You're offline.

**Comment by ballPointPenguin** [comment]
Thank you so much!
I think modifying my .pryrc is a completely workable solution. Thanks for showing how to edit those config vars. My eyes are already feeling more relaxed. :heart_eyes:
